### ISSUE TITLE
Trim TSO/polyA for 10x 5' reads

### ISSUE THREAD

**Issue by songmingl** [ruppinlab/CSI-Microbes-identification#8]
Hi!

I'm currently using this tool to analyze 10x 5' data.

However, it seems that cellranger would not add `ts` and `pa` tag for 5' data, and since the 10x 5' R2 reads is the reverse-complement sequence of mRNA, the position of TSO and ployA (or polyT) is reverse to the 10x 3' R2 reads.

Any suggestion for this kind of data?

Thanks!

**Comment by wir963** [comment]
Hey @songmingl,

When I first wrote this code, I wasn't thinking about 10x 5' data so thanks for bringing this to my attention.

I've analyzed 10x 5' data before using this tool and I know it works for at least some 10x 5' dataset (some of the datasets are intentional infection datasets where the infecting bacteria is known). My best guess as to why it works is because we don't have to worry about the polyA/T tail because it is 5' data (and only the 3' end of mRNA is poly-adenylated). I think the TSO would also be at the 3' end. However, it's possible that it works sub-optimally and I'll need to think about this. 

Are you running into any errors? Or are you just worried about this conceptually?

Best, Welles

**Comment by wir963** [comment]
Hey @songmingl,

The updated CSI-Microbes paper is finally up on biorxiv (https://www.biorxiv.org/content/10.1101/2020.05.14.096230v3) and here's the tweetorial (https://twitter.com/NCIEytanRuppin/status/1652347018709282821). I'm going to close out this issue but please let me know if you have any additional questions and best of luck with your research. 

Best, Welles
